/**
 * ══════════════════════════════════════════════════════════════
 * SL-LMS MOCK SEED DATA — Initial State for Global Store
 * ══════════════════════════════════════════════════════════════
 *
 * Generates realistic seed data for appointments, cases, and
 * payments with proper lifecycle status and deadlines.
 *
 * This data powers the global store on first load.
 * Replace with real API calls when backend is ready.
 */

import { AppointmentStatus, CaseStatus, PaymentStatus } from "@utils/statusEnums";
import { createDeadline } from "@utils/timeHelpers";

// ── Helper: past timestamp ───────────────────────────────────

function pastDate(daysAgo, hoursAgo = 0) {
  return Date.now() - daysAgo * 86400000 - hoursAgo * 3600000;
}

function futureDate(daysAhead, hoursAhead = 0) {
  return Date.now() + daysAhead * 86400000 + hoursAhead * 3600000;
}

// ══════════════════════════════════════════════════════════════
//  SEED APPOINTMENTS
// ══════════════════════════════════════════════════════════════

export function seedAppointments() {
  return [
    // ── Pending lawyer approval (with countdown) ──
    {
      id: "apt-seed-001",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-001",
      lawyerName: "Atty. Kamal Perera",
      lawyerSpecialization: "Criminal Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/32.jpg",
      consultationType: "video",
      caseType: "Criminal Law",
      description: "Bail hearing preparation and strategy discussion",
      urgency: "high",
      selectedDate: new Date(futureDate(3)).toISOString().split("T")[0],
      selectedTime: "10:00 AM",
      consultationFee: 5000,
      status: AppointmentStatus.PENDING_APPROVAL,
      createdAt: Date.now() - 3600000,
      approvalDeadline: createDeadline(23, "hours"),
      approvalDuration: 24 * 3600000,
      paymentDeadline: null,
      paymentDuration: null,
    },
    // ── Approved — awaiting client payment (with countdown) ──
    {
      id: "apt-seed-002",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-002",
      lawyerName: "Atty. Nimalka Fernando",
      lawyerSpecialization: "Family Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/women/44.jpg",
      consultationType: "in-office",
      caseType: "Family Law",
      description: "Custody arrangement consultation — bring relevant documents",
      urgency: "medium",
      selectedDate: new Date(futureDate(5)).toISOString().split("T")[0],
      selectedTime: "02:30 PM",
      consultationFee: 4500,
      status: AppointmentStatus.APPROVED_AWAITING_PAYMENT,
      createdAt: pastDate(1, 2),
      approvalDeadline: pastDate(0, 22),
      approvalDuration: 24 * 3600000,
      approvedAt: pastDate(0, 22),
      paymentDeadline: createDeadline(8, "minutes"),
      paymentDuration: 10 * 60000,
    },
    // ── Confirmed ──
    {
      id: "apt-seed-003",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "phone",
      caseType: "Property Law",
      description: "Land deed review and partition plan discussion",
      urgency: "low",
      selectedDate: new Date(futureDate(7)).toISOString().split("T")[0],
      selectedTime: "11:00 AM",
      consultationFee: 6000,
      status: AppointmentStatus.CONFIRMED,
      createdAt: pastDate(3),
      approvedAt: pastDate(2),
      paymentDeadline: null,
      paidAt: pastDate(2),
    },
    // ── Completed ──
    {
      id: "apt-seed-004",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-005",
      lawyerName: "Atty. Thilini Ratnayake",
      lawyerSpecialization: "Labour Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/women/33.jpg",
      consultationType: "in-office",
      caseType: "Labour Law",
      description: "Wrongful termination initial consultation",
      urgency: "high",
      selectedDate: new Date(pastDate(10)).toISOString().split("T")[0],
      selectedTime: "03:00 PM",
      consultationFee: 4000,
      status: AppointmentStatus.COMPLETED,
      createdAt: pastDate(14),
      approvedAt: pastDate(13),
      paidAt: pastDate(13),
      completedAt: pastDate(10),
    },
    // ── Declined ──
    {
      id: "apt-seed-005",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-004",
      lawyerName: "Atty. Dilini Jayawardena",
      lawyerSpecialization: "Corporate Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/women/65.jpg",
      consultationType: "video",
      caseType: "Corporate Law",
      description: "Business merger advisory",
      urgency: "medium",
      selectedDate: new Date(pastDate(5)).toISOString().split("T")[0],
      selectedTime: "11:00 AM",
      consultationFee: 7500,
      status: AppointmentStatus.DECLINED,
      createdAt: pastDate(8),
      declineReason: "Scheduling conflict — currently in trial proceedings",
      declinedAt: pastDate(7),
    },
    // ── Cancelled ──
    {
      id: "apt-seed-006",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-007",
      lawyerName: "Atty. Priyanka Weerasinghe",
      lawyerSpecialization: "Constitutional Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/61.jpg",
      consultationType: "video",
      caseType: "Constitutional Law",
      description: "Fundamental rights petition discussion",
      urgency: "low",
      selectedDate: new Date(pastDate(2)).toISOString().split("T")[0],
      selectedTime: "10:00 AM",
      consultationFee: 10000,
      status: AppointmentStatus.CANCELLED,
      createdAt: pastDate(6),
      cancelReason: "Client requested reschedule to next week",
      cancelledAt: pastDate(4),
    },

    // ══════════════════════════════════════════════════════════
    //  LAWYER LWR-003 — Additional appointments for lawyer view
    // ══════════════════════════════════════════════════════════

    // ── Pending approval — new client request for LWR-003 ──
    {
      id: "apt-seed-007",
      clientId: "USR-2026-0002",
      clientName: "Tharushi Gunasekara",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "video",
      caseType: "Property Law",
      description: "Land ownership dispute in Negombo — inherited property with multiple claimants. Seeking legal opinion on partition options.",
      urgency: "high",
      selectedDate: new Date(futureDate(4)).toISOString().split("T")[0],
      selectedTime: "10:00 AM",
      consultationFee: 6000,
      status: AppointmentStatus.PENDING_APPROVAL,
      createdAt: Date.now() - 7200000,
      approvalDeadline: createDeadline(16, "hours"),
      approvalDuration: 24 * 3600000,
      paymentDeadline: null,
      paymentDuration: null,
    },
    // ── Pending approval — another request for LWR-003 ──
    {
      id: "apt-seed-008",
      clientId: "USR-2026-0003",
      clientName: "Roshan Abeywickrama",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "in-office",
      caseType: "Labour Law",
      description: "Terminated without notice after 8 years of service. Employer refuses severance — need urgent legal representation.",
      urgency: "urgent",
      selectedDate: new Date(futureDate(2)).toISOString().split("T")[0],
      selectedTime: "02:00 PM",
      consultationFee: 5000,
      status: AppointmentStatus.PENDING_APPROVAL,
      createdAt: Date.now() - 3600000,
      approvalDeadline: createDeadline(22, "hours"),
      approvalDuration: 24 * 3600000,
      paymentDeadline: null,
      paymentDuration: null,
    },
    // ── Pending approval — third request for LWR-003 ──
    {
      id: "apt-seed-009",
      clientId: "USR-2026-0004",
      clientName: "Malika Senanayake",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "phone",
      caseType: "Civil Law",
      description: "Contract dispute with a construction company. Project abandoned midway — significant financial loss incurred.",
      urgency: "medium",
      selectedDate: new Date(futureDate(6)).toISOString().split("T")[0],
      selectedTime: "11:00 AM",
      consultationFee: 5500,
      status: AppointmentStatus.PENDING_APPROVAL,
      createdAt: Date.now() - 14400000,
      approvalDeadline: createDeadline(20, "hours"),
      approvalDuration: 24 * 3600000,
      paymentDeadline: null,
      paymentDuration: null,
    },
    // ── Approved awaiting payment — LWR-003 ──
    {
      id: "apt-seed-010",
      clientId: "USR-2026-0005",
      clientName: "Kamal Jayawardena",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "in-office",
      caseType: "Property Law",
      description: "Boundary dispute with neighboring property — survey discrepancies need legal evaluation.",
      urgency: "medium",
      selectedDate: new Date(futureDate(5)).toISOString().split("T")[0],
      selectedTime: "09:30 AM",
      consultationFee: 6500,
      status: AppointmentStatus.APPROVED_AWAITING_PAYMENT,
      createdAt: pastDate(0, 6),
      approvedAt: pastDate(0, 3),
      approvalDeadline: pastDate(0, 3),
      approvalDuration: 24 * 3600000,
      paymentDeadline: createDeadline(7, "minutes"),
      paymentDuration: 10 * 60000,
    },
    // ── Confirmed — upcoming consultation for LWR-003 ──
    {
      id: "apt-seed-011",
      clientId: "USR-2026-0006",
      clientName: "Lakshmi Wijesinghe",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "video",
      caseType: "Property Law",
      description: "Consultation regarding property boundary dispute and potential survey requirements.",
      urgency: "low",
      selectedDate: new Date(futureDate(2)).toISOString().split("T")[0],
      selectedTime: "10:30 AM",
      consultationFee: 6000,
      status: AppointmentStatus.CONFIRMED,
      createdAt: pastDate(2),
      approvedAt: pastDate(1, 12),
      paidAt: pastDate(1, 11),
    },
    // ── Completed — eligible for case creation for LWR-003 ──
    {
      id: "apt-seed-012",
      clientId: "USR-2026-0002",
      clientName: "Tharushi Gunasekara",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "in-office",
      caseType: "Property Law",
      description: "Land deed review for inherited property — partition feasibility assessment.",
      urgency: "medium",
      selectedDate: new Date(pastDate(5)).toISOString().split("T")[0],
      selectedTime: "03:00 PM",
      consultationFee: 6000,
      status: AppointmentStatus.COMPLETED,
      createdAt: pastDate(12),
      approvedAt: pastDate(11),
      paidAt: pastDate(11),
      completedAt: pastDate(5),
    },
    // ── Completed — another completed for LWR-003 ──
    {
      id: "apt-seed-013",
      clientId: "USR-2026-0007",
      clientName: "Anura Wickramasinghe",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "phone",
      caseType: "Civil Law",
      description: "Commercial lease agreement review and breach assessment.",
      urgency: "low",
      selectedDate: new Date(pastDate(8)).toISOString().split("T")[0],
      selectedTime: "11:00 AM",
      consultationFee: 5500,
      status: AppointmentStatus.COMPLETED,
      createdAt: pastDate(15),
      approvedAt: pastDate(14),
      paidAt: pastDate(14),
      completedAt: pastDate(8),
    },
    // ── Declined by LWR-003 ──
    {
      id: "apt-seed-014",
      clientId: "USR-2026-0008",
      clientName: "Chaminda Rathnayake",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      consultationType: "video",
      caseType: "Criminal Law",
      description: "Criminal defense consultation — outside area of specialization.",
      urgency: "high",
      selectedDate: new Date(pastDate(3)).toISOString().split("T")[0],
      selectedTime: "04:00 PM",
      consultationFee: 7000,
      status: AppointmentStatus.DECLINED,
      createdAt: pastDate(6),
      declineReason: "Criminal law falls outside my area of practice. I can recommend a colleague.",
      declinedAt: pastDate(5),
    },
  ];
}

// ══════════════════════════════════════════════════════════════
//  SEED CASES
// ══════════════════════════════════════════════════════════════

export function seedCases() {
  return [
    {
      id: "case-seed-001",
      appointmentId: "apt-seed-004",
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-005",
      lawyerName: "Atty. Thilini Ratnayake",
      lawyerSpecialization: "Labour Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/women/33.jpg",
      caseType: "Labour Law",
      title: "Employment Wrongful Termination",
      description: "Claim against former employer for unfair dismissal under the Shop & Office Act. Seeking reinstatement and compensation for lost wages.",
      status: CaseStatus.ACTIVE,
      createdAt: pastDate(9),
      documents: [
        { id: "doc-c1-1", name: "Employment_Contract.pdf", size: 1200000, uploadedAt: pastDate(8), type: "pdf" },
        { id: "doc-c1-2", name: "Termination_Letter.pdf", size: 890000, uploadedAt: pastDate(7), type: "pdf" },
        { id: "doc-c1-3", name: "Salary_Slips_2025.xlsx", size: 340000, uploadedAt: pastDate(6), type: "xlsx" },
      ],
      messages: [],
      timeline: [
        { date: pastDate(9), event: "Case Created", status: "completed" },
        { date: pastDate(7), event: "Documents Submitted", status: "completed" },
        { date: pastDate(4), event: "Demand Letter Sent", status: "completed" },
        { date: futureDate(20), event: "Labour Tribunal Hearing", status: "upcoming" },
      ],
      totalFees: 35000,
      paidAmount: 4000,
      nextPaymentDeadline: null,
      progress: 40,
    },
    {
      id: "case-seed-002",
      appointmentId: null,
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      caseType: "Property Law",
      title: "Property Dispute — Land Partition",
      description: "Partition action regarding inherited property in Galle district. Involves three co-owners seeking equitable division.",
      status: CaseStatus.PAYMENT_PENDING,
      createdAt: pastDate(60),
      documents: [
        { id: "doc-c2-1", name: "Land_Deed_Scan.pdf", size: 2450000, uploadedAt: pastDate(55), type: "pdf" },
        { id: "doc-c2-2", name: "Surveyor_Report.pdf", size: 5800000, uploadedAt: pastDate(30), type: "pdf" },
      ],
      messages: [],
      timeline: [
        { date: pastDate(60), event: "Case Filed", status: "completed" },
        { date: pastDate(45), event: "First Hearing", status: "completed" },
        { date: pastDate(30), event: "Surveyor Report Submitted", status: "completed" },
        { date: pastDate(10), event: "Objections Heard", status: "completed" },
        { date: futureDate(12), event: "Next Hearing", status: "upcoming" },
      ],
      totalFees: 85000,
      paidAmount: 56000,
      nextPaymentDeadline: createDeadline(5, "days"),
      progress: 65,
    },
    {
      id: "case-seed-003",
      appointmentId: null,
      clientId: "USR-2026-0001",
      clientName: "Ashan Bandara",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      caseType: "Property Law",
      title: "Tenancy Agreement Dispute",
      description: "Dispute with landlord over tenancy agreement violations. Successfully resolved with favorable settlement.",
      status: CaseStatus.CLOSED,
      createdAt: pastDate(120),
      closedAt: pastDate(15),
      documents: [],
      messages: [],
      timeline: [
        { date: pastDate(120), event: "Case Filed", status: "completed" },
        { date: pastDate(90), event: "Mediation Attempted", status: "completed" },
        { date: pastDate(50), event: "Court Hearing", status: "completed" },
        { date: pastDate(15), event: "Settlement Reached", status: "completed" },
      ],
      totalFees: 45000,
      paidAmount: 45000,
      nextPaymentDeadline: null,
      progress: 100,
    },
    // ── Active case for LWR-003 from completed consultation ──
    {
      id: "case-seed-004",
      appointmentId: "apt-seed-013",
      clientId: "USR-2026-0007",
      clientName: "Anura Wickramasinghe",
      lawyerId: "LWR-003",
      lawyerName: "Atty. Ranjan de Silva",
      lawyerSpecialization: "Property Law",
      lawyerAvatar: "https://randomuser.me/api/portraits/men/45.jpg",
      caseType: "Civil Law",
      title: "Commercial Lease Breach",
      description: "Breach of commercial property lease agreement by tenant. Seeking compensation for damages and early termination costs.",
      status: CaseStatus.ACTIVE,
      createdAt: pastDate(7),
      documents: [
        { id: "doc-c4-1", name: "Lease_Agreement.pdf", size: 1800000, uploadedAt: pastDate(6), type: "pdf" },
        { id: "doc-c4-2", name: "Damage_Assessment.pdf", size: 2200000, uploadedAt: pastDate(4), type: "pdf" },
      ],
      messages: [
        { id: "msg-c4-1", sender: "client", senderName: "Anura Wickramasinghe", text: "I have attached the original lease agreement for your review.", timestamp: pastDate(6) },
        { id: "msg-c4-2", sender: "lawyer", senderName: "Atty. Ranjan de Silva", text: "Thank you, I have reviewed the agreement. The breach clause in Section 12 is quite clear. We have strong grounds.", timestamp: pastDate(5, 20) },
      ],
      timeline: [
        { date: pastDate(7), event: "Case Created", status: "completed" },
        { date: pastDate(6), event: "Documents Submitted", status: "completed" },
        { date: pastDate(3), event: "Demand Letter Drafted", status: "completed" },
        { date: futureDate(14), event: "Mediation Session", status: "upcoming" },
      ],
      totalFees: 55000,
      paidAmount: 5500,
      nextPaymentDeadline: null,
      progress: 25,
    },
  ];
}

// ══════════════════════════════════════════════════════════════
//  SEED PAYMENTS
// ══════════════════════════════════════════════════════════════

export function seedPayments() {
  return [
    // ── Pending payment for apt-seed-002 ──
    {
      id: "pay-seed-001",
      appointmentId: "apt-seed-002",
      caseId: null,
      clientId: "USR-2026-0001",
      lawyerId: "LWR-002",
      amount: 4500,
      type: "consultation_fee",
      status: PaymentStatus.PENDING,
      createdAt: Date.now() - 120000,
      deadline: createDeadline(8, "minutes"),
      paidAt: null,
      description: "Consultation fee — Atty. Nimalka Fernando",
    },
    // ── Successful payment for apt-seed-003 ──
    {
      id: "pay-seed-002",
      appointmentId: "apt-seed-003",
      caseId: null,
      clientId: "USR-2026-0001",
      lawyerId: "LWR-003",
      amount: 6000,
      type: "consultation_fee",
      status: PaymentStatus.SUCCESS,
      createdAt: pastDate(2, 4),
      deadline: null,
      paidAt: pastDate(2, 3),
      description: "Consultation fee — Atty. Ranjan de Silva",
    },
    // ── Successful payment for apt-seed-004 ──
    {
      id: "pay-seed-003",
      appointmentId: "apt-seed-004",
      caseId: null,
      clientId: "USR-2026-0001",
      lawyerId: "LWR-005",
      amount: 4000,
      type: "consultation_fee",
      status: PaymentStatus.SUCCESS,
      createdAt: pastDate(13, 2),
      deadline: null,
      paidAt: pastDate(13),
      description: "Consultation fee — Atty. Thilini Ratnayake",
    },
    // ── Pending case payment for case-seed-002 ──
    {
      id: "pay-seed-004",
      appointmentId: null,
      caseId: "case-seed-002",
      clientId: "USR-2026-0001",
      lawyerId: "LWR-003",
      amount: 29000,
      type: "case_fee",
      status: PaymentStatus.PENDING,
      createdAt: pastDate(2),
      deadline: createDeadline(5, "days"),
      paidAt: null,
      description: "Legal fees — Property Dispute Land Partition (Phase 3)",
    },
    // ── Historical payments ──
    {
      id: "pay-seed-005",
      appointmentId: null,
      caseId: "case-seed-002",
      clientId: "USR-2026-0001",
      lawyerId: "LWR-003",
      amount: 30000,
      type: "case_fee",
      status: PaymentStatus.SUCCESS,
      createdAt: pastDate(35),
      deadline: null,
      paidAt: pastDate(34),
      description: "Legal fees — Property Dispute (Phase 2)",
    },
    {
      id: "pay-seed-006",
      appointmentId: null,
      caseId: "case-seed-002",
      clientId: "USR-2026-0001",
      lawyerId: "LWR-003",
      amount: 20000,
      type: "case_fee",
      status: PaymentStatus.SUCCESS,
      createdAt: pastDate(58),
      deadline: null,
      paidAt: pastDate(57),
      description: "Legal fees — Property Dispute (Phase 1)",
    },
    {
      id: "pay-seed-007",
      appointmentId: null,
      caseId: "case-seed-003",
      clientId: "USR-2026-0001",
      lawyerId: "LWR-003",
      amount: 45000,
      type: "case_fee",
      status: PaymentStatus.SUCCESS,
      createdAt: pastDate(90),
      deadline: null,
      paidAt: pastDate(89),
      description: "Legal fees — Tenancy Agreement Dispute (Full)",
    },
  ];
}
